### PR TITLE
Fix Compatibility with Form Extensions

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

This was missed during @wbloszyk PRs because the dependency between this and CoreBundle was not explicit

## Changelog

```markdown
### Removed
- SonataCoreBundle dependencies
- Support for Symfony < 4.4
```

### CODE REVIEW

**Review by core23 — DISMISSED** [review]

**Review by VincentLanglet — DISMISSED** [review]

**Review by wbloszyk — DISMISSED** [review]

**Comment by jordisala1991** [comment]
Had to bump to sf 4.4 and php 7.2 too, in order to get the prefer lowest build runing

**Review by wbloszyk — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by PierreEkino** [comment]
Is it possible to have a release for it ? Thanks a lot 👍

**Comment by wbloszyk** [comment]
@greg0ire Can you release it?

**Comment by qsomazzi** [comment]
@sonata-project/release-managers little update on this, can we have a release please ?

**Comment by VincentLanglet** [comment]
Sorry, I'm on it https://github.com/sonata-project/SonataArticleBundle/pull/175

**Pull request merged**
