### PR TITLE
define FragmentAdmin not final

### PR DESCRIPTION
**Pull request by vlaurier**
## Changelog

```markdown
### Changed
- FragmentAdmin class is not final anymore
```

## Subject

For custom purpose I need to override access behaviour to fragments, so I would like to be able to extend the FragmentAdmin class.

### CODE REVIEW

**Comment by greg0ire** [comment]
> For custom purpose I need to override access behaviour to fragments, so I would like to be able to extend the FragmentAdmin class.

Can you elaborate? What do you need to do exactly?

**Comment by core23** [comment]
Can you use an `AdminExtension` for this?

**Comment by vlaurier** [comment]
@greg0ire: In the application, I have specific rules for rights on Articles. A user can edit only an article if he is in the same category than the author for example... some stuff like that.
I did it for article by overriding the "isGranted" method of ArticleAdmin.
But, as Fragments are a collection in Article Entity, I need to apply the same rights to the fragments to implement what I want.

@core23: no idea, I have to look what AdminExtension is... Thanks for the idea.

**Comment by greg0ire** [comment]
If you use the role security handler, I think you can solve this with a simple Voter. The handler just computes a role, then it's standard sf

**Comment by vlaurier** [comment]
Thanks for you reply, I'm going to try that way.

**Pull request closed without merging**
