### PR TITLE
[FEAT] : Overridable edit_collection_fragment template

### PR DESCRIPTION
**Pull request by c-Rolland**
## Subject

I am targeting this branch to surround the different parts of **edit_collection_fragment.html.twig** template with blocks to make it more overridable.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by c-Rolland** [comment]
@greg0ire @OskarStark can you tag it pls ? ^^

**Comment by c-Rolland** [comment]
hello, someone can tag this pls ? @core23 @OskarStark @greg0ire

**Comment by greg0ire** [comment]
Expect a release tonight

**Comment by greg0ire** [comment]
There should have been a changelog, I'm going to try to make one up.

**Pull request merged**
