### PR TITLE
Fix doctrine default value

### PR DESCRIPTION
**Pull request by qsomazzi**
## Changelog

```markdown
### Fixed
- Doctrine mapping for Fragment
```

## Subject

Quick fix on doctrine mapping default value for type boolean

### CODE REVIEW

**Comment by greg0ire** [comment]
I think you are right, but [the documentation says default values are not supported](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/faq.html#how-can-i-add-default-values-to-a-column)… that's strange.

**Comment by qsomazzi** [comment]
I think it's the default key that isn't supported like here 
https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/config/doctrine/BaseSite.orm.xml#L10

If i let the old value I've got this error on `doctrine:schema:update`
````
[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE TABLE article__fragment (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, backoffice_title VARCHAR(255) NOT NULL, position INT DEFAULT NULL, settings LONGTEXT NOT NULL COMMENT '(DC2Type:json)', type VARCHAR(64
  ) NOT NULL, enabled TINYINT(1) DEFAULT 'true' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3F5800A87294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'enabled'

**Comment by greg0ire** [comment]
If you use an integer, is it actually taken into account? Do you actually see the default value in the table definition?

**Comment by greg0ire** [comment]
According to the docs, the right fix would be to drop the default value in the mapping, and use it inside the class directly instead.

**Comment by qsomazzi** [comment]
If I use an integer, it's correctly taken into account. But I will follow the doc, and remove the default value and set it in the class.

**Comment by greg0ire** [comment]
Okay as you wish

**Comment by qsomazzi** [comment]
Done :)

**Comment by greg0ire** [comment]
Uuuuh… I don't see any change in any php class…

**Comment by qsomazzi** [comment]
https://github.com/sonata-project/SonataArticleBundle/blob/master/Model/AbstractFragment.php#L32

**Comment by qsomazzi** [comment]
was already done this part :)

**Comment by greg0ire** [comment]
Oh it's already there… ok!

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
To be squash-merged with the following message : 

```
Remove default value in fragment metadata

It produces invalid SQL, and is not recommended, see
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/faq.html#how-can-i-add-default-values-to-a-column
```

**Pull request merged**
